sprint_1
AliyevHrn/middle.messenger.praktikum.yandex pull request #1
Opened 2021-07-17 22:55 UTC by AliyevHrn

2021-07-18 07:29 UTC, DmitryKhitrin commented on package.json
> +    "start": "./node_modules/.bin/parcel src/index.pug -p 3000",
Запускать parcel лучше через из cli:

`"start": "parcel src/index.pug -p 3000"`

2021-07-18 07:34 UTC, DmitryKhitrin requested changes
Привет, спасибо за отличную работу! Но к сожалению я не смог найти некоторые ТЗ:

- Настройте Express-сервер с раздачей статики — файла index.html;
- добавьте домен из Netlify в README.md;

Доделайте их пожалуйста)

2021-07-18 07:34 UTC, DmitryKhitrin commented on src/pages/chatMessages/index.html
> +                        <span class="chatList__item__lastDate">12:00</span>
Тут подойдет тег `<time>`

2021-07-18 07:34 UTC, DmitryKhitrin commented on src/pages/chatMessages/index.html
> +                        <div class="chat__messages__list">
Списки принято верстать при помощи тега `<ul>`, так будет семантически корректней

2021-07-18 15:14 UTC, AliyevHrn commented on src/pages/chatMessages/index.html
> +                        <span class="chatList__item__lastDate">12:00</span>
Привет!
Настроил express, локально все билдится и запускается, на сервере как я понял он не нужен.

Ссылку на домен netlify добавил в readme.md.
Есть проблема с деплоем на netlify, сначала происхидит успешный билд, а потом ошибка:
unknown: Entry /opt/build/repo/src/index.pug does not exist
Error: Cannot find module 'ansi-html'

Пытаюсь понять, что не так ((

2021-07-18 15:15 UTC, AliyevHrn commented on src/pages/chatMessages/index.html
> +                        <div class="chat__messages__list">
Спасибо, исправил!

2021-07-18 15:16 UTC, AliyevHrn commented on package.json
> +    "start": "./node_modules/.bin/parcel src/index.pug -p 3000",
Понял, исправил!

2021-07-19 06:26 UTC, DmitryKhitrin commented on server.js
> +const PORT = 3000;
Часто удобно иметь возможность прокинуть порт снаружи:

`const port = process.env.PORT || PORT;`

2021-07-19 06:26 UTC, DmitryKhitrin commented on src/pages/chatMessages/index.html
> +                        <span class="chatList__item__lastDate">12:00</span>
Скорее всего в собранном проекте нет файла с расширением pug, после билда он должен стать index.html вероятно

2021-07-19 06:27 UTC, DmitryKhitrin approved these changes

2021-07-19 07:59 UTC, merged